from src.GUI.const.Sizes import \
    WINDOW_SIZE,BOARD_SIZE,MASS_SIZE,END_SURFACE_SIZE,\
    PIECE_POINTS,BOARD_SHAPE
    
from src.GUI.const.Colors import PIECE_COLOR, BOARD_COLOR, WIN_SURFACE_COLOR